CREATE TABLE Users 
(
	Id INT PRIMARY KEY IDENTITY(1,1),
	UserName VARCHAR(50) NOT NULL,
	Password VARCHAR(50) NOT NULL,
	Role VARCHAR(20) NOT NULL,
	Status VARCHAR(20) NOT NULL,
	Date DATE NOT NULL
)
SELECT * FROM Users